jobs:
- job: Windows

  pool:
    vmImage: 'windows-2019'

  steps:
  - task: GitVersion@5
    inputs:
      updateAssemblyInfo: false
      configFilePath: gitversion.yml

  - task: MSBuild@1
    inputs:
      solution: src/Uno.Wasm.WebSockets.sln
      msbuildArguments: /r /p:Configuration=Release "/p:PackageOutputPath=$(build.artifactstagingdirectory)\nuget" "/p:PackageVersion=%GITVERSION_FullSemVer%" "/p:InformationalVersion=%GITVERSION_InformationalVersion%"  /detailedsummary

  - task: PowerShell@2
    displayName: Authenticode Sign Packages
    inputs:
      filePath: build/Sign-Package.ps1
    env:
      SignClientUser: $(SignClientUser)
      SignClientSecret: $(SignClientSecret)
      SignPackageName: "Uno.Wasm.WebSockets"
      SignPackageDescription: "Uno.Wasm.WebSockets"
      ArtifactDirectory: $(build.artifactstagingdirectory)
    condition: and(succeeded(), not(eq(variables['build.reason'], 'PullRequest')), not(eq(variables['SignClientSecret'], '')), not(eq(variables['SignClientUser'], '')))
 
  - task: CopyFiles@2
    inputs:
      SourceFolder: $(build.sourcesdirectory)/src/WasmWebSocketsSample/WasmWebSocketsSample.Wasm/bin/Release/netstandard2.0/dist
      Contents: "**/*.*"
      TargetFolder: $(build.artifactstagingdirectory)\wasm
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: uno-wasm-websockets-drop
      ArtifactType: Container
